shot_bin = read_float_binary("desert_eagle_357");
shot = (2).*shot_bin(40:5000);
%shot = (1.2).*shot_bin(23000:27000);
shot_lin = transpose(shot);
shot_match_filt = fliplr(shot_lin);
sens_input = read_float_binary("desert_eagle_357_crowd_shot_single");
sens_out = conv(sens_input,shot_match_filt);
csvwrite("/home/ben/Desktop/senior_design/shot_taps/desert_eagle_357_taps.txt",shot_match_filt)
(fliplr(shot_lin))(1:6)
shot_match_filt(1:6)
size(shot_bin)
size(shot)
size(shot_lin)
size(shot_match_filt)
size(sens_input)
size(sens_out)
figure(1)
subplot(2,3,1)
plot(shot_bin)
title("shot from bin file")
subplot(2,3,2)
plot(shot)
title("truncated shot")
subplot(2,3,3)
plot(shot_lin)
title("transposed var 'shot'")
subplot(2,3,4)
plot(shot_match_filt)
title("matched filter (reversed shot_lin)")
subplot(2,3,5)
plot(sens_input)
title("sensor input from crowd")
subplot(2,3,6)
plot(sens_out)
title("output of matched filter")
figure(2)
subplot(1,3,1)
plot(sens_input)
title("sensor input signal from microphone")
subplot(1,3,2)
plot(shot_match_filt)
title("filter that signal is run through")
subplot(1,3,3)
plot(sens_out)
title("sensor output")
r = dlmread("/home/ben/Desktop/senior_design/shot_taps/desert_eagle_357_taps.txt", ",");
size(r)
r(1:6)
figure(6)
plot(r)